image: docker:git
services:
  - docker:dind

stages:
  - build
  - publish

variables:
  REGISTRY_ENDPOINT: registry-special.tenforce.com
  REGISTRY_IMAGE: registry-special.tenforce.com/special/demonstrator-platform
  DOCKER_HOST: "tcp://docker:2375"

before_script:
  - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_ENDPOINT}

validate:
  stage: build
  image:
    name: docker/compose:1.22.0
    entrypoint: [""]
  script:
    # Validate regular local deploy
    - KEYCLOAK_ENDPOINT=localhost docker-compose config
    # Validate swarm deploy
    - KEYCLOAK_ENDPOINT=test.example.com KEYCLOAK_PASSWORD=test RECOVERY_EMAIL=test@example.com docker-compose -f docker-compose.yml -f docker-compose.production.yml config

publish-github:
  stage: publish
  variables:
    GIT_STRATEGY: clone
  script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add /dev/stdin
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git push ${GITHUB_REMOTE} master
  only:
    - master
# Two seperate jobs so both remotes can be offline / fail without impacting the other sync job
publish-vienna:
  stage: publish
  variables:
    GIT_STRATEGY: clone
  script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add /dev/stdin
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git push ${VIENNA_REMOTE} master
  only:
    - master
