version: "3.4"

services:
  welcome-page:
    restart: on-failure:3
  mobile-frontend:
    restart: on-failure:3
  transparency-backend:
    restart: on-failure:3
    ports:
      - "555:80"
  transparency-frontend:
    restart: on-failure:3
    ports:
      - "82:80"
  consent-management-frontend:
    restart: on-failure:3
  consent-management-backend:
    restart: on-failure:3
  policy-admin-frontend:
    restart: on-failure:3
  compliance-checker:
    restart: on-failure:3
    ports:
      - "8080:8080"
  rethinkdb:
    restart: on-failure:3
  zookeeper:
    restart: on-failure:3
  kafka:
    restart: on-failure:3
  kong-database:
    restart: on-failure:3
  kong-database-migrations:
    restart: on-failure:3
  kong:
    restart: on-failure:3
  kong-config:
    volumes:
    - ./kong_config.json:/config.json

