version: '3.4'
services:
  mobile-frontend:
    image: registry-special.tenforce.com/special/mobile-frontend:1.0.0

  transparency-frontend:
    image: registry-special.tenforce.com/special/demonstrator-transparency-frontend:1.0.0

  transparency-backend:
    image: registry-special.tenforce.com/special/kafka-sse-proxy:latest
    environment:
      BROKERS: kafka:9092
      TOPIC: checked-application-logs

  dispatcher:
    image: registry-special.tenforce.com/special/demonstrator-dispatcher:1.0.0
    ports:
      - "80:80"
    environment:
      DOMAIN: $DOMAIN:80
      EMAIL: 'off'
      POLICY_CRUD_UI: http://policy-admin-frontend
      CONSENT_UI: http://consent-management-frontend
      TRANSPARENCY_UI: http://transparency-frontend
      TRANSPARENCY_BACKEND: http://transparency-backend
      CONSENT_MANAGEMENT_BACKEND: http://consent-management-backend
      KEYCLOAK: http://keycloak:8080
      MOBILE_FRONTEND: http://mobile-frontend

  consent-management-frontend:
    image: registry-special.tenforce.com/special/demonstrator-consent-management-frontend:1.0.0

  consent-management-backend:
    image: registry-special.tenforce.com/special/consent-management-backend:1.0.0
    environment:
      SERVER_HOST: consent-management-backend # Please don't do this, just bind to 0.0.0.0 in the container
      SERVER_PORT: 80
      RETHINKDB_HOST: rethinkdb
      RETHINKDB_PORT: 28015
      KAFKA_BROKER_LIST: kafka:9092
      CHANGE_LOGS_TOPIC: policies-audit
      FULL_POLICIES_TOPIC: full-policies
      AUTH_LOGIN_ENDPOINT: http://$DOMAIN/auth/realms/master/protocol/openid-connect/auth
      AUTH_CLIENT_ID: special-platform
      AUTH_CLIENT_SECRET: special-platform-secret
      AUTH_USERINFO_ENDPOINT: http://$DOMAIN/auth/realms/master/protocol/openid-connect/userinfo
      AUTH_TOKEN_ENDPOINT: http://$DOMAIN/auth/realms/master/protocol/openid-connect/token
      SERVER_AUTH_CALLBACK_ENDPOINT: http://$DOMAIN/callback

  policy-admin-frontend:
    image: registry-special.tenforce.com/special/demonstrator-policy-admin-frontend:1.0.0

  compliance-checker:
    image: registry-special.tenforce.com/special/compliance-checker:1.0.0
    environment:
      KAFKA_URL_LIST: "kafka:9092"
      KAFKA_CLIENT_ID: 1
      KAFKA_TOPIC_POLICY: "full-policies"
      KAFKA_TOPIC_ACCESS: "application-logs"
      KAFKA_TOPIC_CONSENT: "checked-application-logs"

  rethinkdb:
    image: rethinkdb:2.3
    volumes:
      - rethinkdb:/data

  log-generator:
    image: registry-special.tenforce.com/special/demonstrator-log-generator:1.0.0
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      RATE: 1s
      KAFKA_BROKER_LIST: kafka:9092
      KAFKA_TOPIC: application-logs
      KEYCLOAK_ENDPOINT: http://$DOMAIN/auth
      KEYCLOAK_USER: demonstrator-generator
      KEYCLOAK_PASSWORD: demonstrator-generator
      BACKEND_ENDPOINT: http://consent-management-backend

  # Kafka setup (should maybe go in external deployment)
  zookeeper:
    image: zookeeper:latest
    volumes:
      - zoodata:/data
      - zoolog:/datalog

  # Networking setup is not perfect yet and will most likely change slightly once
  # I get around to testing it with multiple nodes on swarm. For local dev the current setup works fine
  # TODO: save data in a volume (or mount from host)
  kafka:
    image: wurstmeister/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper
    environment:
      # HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_HOSTNAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: application-logs:1:1,full-policies:1:1:compact,policies-audit:1:1,checked-application-logs:1:1
    volumes:
      - kafkalogs:/kafka

  # Keycloak (authentication) setup (should maybe go into an external deployment)
  # TODO: move secrets into docker secrets
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_VENDOR: POSTGRES
      DB_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: 'true'
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloakdb:/var/lib/postgresql/data
  keycloak-init:
    image: registry-special.tenforce.com/special/keycloak-init:latest
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      CLIENT_REDIRECT_URI: http://$DOMAIN/callback/*

volumes:
  keycloakdb:
    driver: local
  rethinkdb:
    driver: local
  kafkalogs:
    driver: local
  zoodata:
    driver: local
  zoolog:
    driver: local
