version: '2.1'
services:
  consent-ui:
    image: ubuntu
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - dispatcher:backend

  policy-checking-frontend:
    image: ubuntu
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    links:
      - dispatcher:backend

  overview-ui:
    image: ubuntu
    links:
      - dispatcher:backend
    ports:
      - "82:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  push-tester:
    image: ubuntu
    ports:
      - "555:80"

  dispatcher:
    image: ubuntu
    # image: semtech/mu-dispatcher:1.0.1
    # links:
    #   - resource:resource
    # volumes:
    #   - ./config/dispatcher:/config
    ports:
      - "444:80"

  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://special.org/application"
    volumes:
      - ./database:/var/lib/virtuoso/db
      - ./config/database/data_to_load:/var/lib/virtuoso/db/toLoad
    ports:
      - "8890:8890"

  resource:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      BOOT: mu-cl-resources

  consent-backend:
    image: ubuntu

  overview-backend:
    image: ubuntu

  compliance-checker:
    image: ubuntu

  zookeeper:
    image: flowofcontrol/docker-zookeeper

  kafka:
    image: flowofcontrol/docker-kafka
    depends_on:
      - zookeeper
    volumes:
      - ./config/kafka:/kafka-config
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
