version: '2.1'
services:
  consent-ui:
    build: ./consent-management-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

  policy-checking-frontend:
    build: ./policy-checking-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    links:
      - dispatcher:backend

  overview-ui:
      build: ./overview-ui/
      links:
        - dispatcher:backend
      ports:
        - 80:80
      volumes:
        - ./config/nginx:/etc/nginx/conf.d

  push-tester:
      build: ./push-tester
      ports:
        - "555:80"

  dispatcher:
    build: ./dispatcher-caddy
    # image: semtech/mu-dispatcher:1.0.1
    # links:
    #   - resource:resource
    # volumes:
    #   - ./config/dispatcher:/config
    ports:
      - "444:80"
  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://special.org/application"
    volumes:
      - ./database:/var/lib/virtuoso/db
      - ./config/database/data_to_load:/var/lib/virtuoso/db/toLoad
    ports:
      - "8890:8890"

  consent-backend:
    image: ubuntu

  overview-backend:
    image: ubuntu

  compliance-checker:
    image: ubuntu

  zookeeper:
    image: flowofcontrol/docker-zookeeper
  kafka:
    image: flowofcontrol/docker-kafka
    depends_on:
      - zookeeper
    volumes:
      - ./config/kafka:/kafka-config
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
