version: '3.4'
services:
  transparency-backend:
    ports:
      - "555:80"
  transparency-frontend:
    ports:
      - "82:80"
  compliance-checker:
    ports:
      - "8080:8080"
  keycloak-init:
    build: keycloak-init/
