version: '2'
services:
  consent-management-frontend:
    build: ./consent-management-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - dispatcher:backend
  policy-checking-frontend:
    build: ./policy-checking-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    links:
      - dispatcher:backend
  dispatcher:
    build: ./dispatcher-caddy
    # image: semtech/mu-dispatcher:1.0.1
    # links:
    #   - resource:resource
    # volumes:
    #   - ./config/dispatcher:/config
    ports:
      - "444:80"
  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./database:/var/lib/virtuoso/db
      - ./config/database/data_to_load:/var/lib/virtuoso/db/toLoad
    ports:
      - "8890:8890"
  delta:
    image: semtech/mu-delta-service:beta-0.12
    links:
      - database:database
    environment:
      - CONFIGFILE=/config/config.properties
      - SUBSCRIBERSFILE=/config/subscribers.json
    volumes:
      - ./config/delta:/config
  resource:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - delta:database
    volumes:
      - ./config/resources:/config
    environment:
      BOOT: mu-cl-resources

  push-tester:
    build: ./push-tester
    ports:
      - "555:80"
