version: "3.4"

x-default-deploy:
  &default-deploy
  restart_policy:
    condition: on-failure
    max_attempts: 5
x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "1m"
    max-file: "1"
  # TODO: Add gliderlabs/logspout as a global service in a separate stack so we can pipe logs to an external service (eg: papertrail)

services:
  welcome-page:
    deploy: *default-deploy
    logging: *default-logging
  mobile-frontend:
    deploy: *default-deploy
    logging: *default-logging

  transparency-frontend:
    deploy: *default-deploy
    logging: *default-logging

  transparency-backend:
    deploy: *default-deploy
    logging: *default-logging

  consent-management-frontend:
    deploy: *default-deploy
    logging: *default-logging

  consent-management-backend:
    deploy: *default-deploy
    logging: *default-logging

  mongo-db:
    deploy:
      placement:
        constraints:
          - node.labels.type == rethinkdb
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging: *default-logging

  mongo-rs-setup:
    deploy:
      placement:
        constraints:
          - node.labels.type == rethinkdb
      restart_policy:
        condition: none
    logging: *default-logging

  policy-admin-frontend:
    deploy: *default-deploy
    logging: *default-logging

  compliance-checker:
    deploy: *default-deploy
    logging: *default-logging

  log-generator:
    deploy:
      restart_policy:
        condition: any
    logging: *default-logging

  zookeeper:
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging: *default-logging

  kafka:
    environment:
      KAFKA_BROKER_ID: 0
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging: *default-logging

  kong-database:
    deploy: *default-deploy
    logging: *default-logging

  kong-database-migrations:
    deploy:
      restart_policy:
        condition: none
    logging: *default-logging

  kong:
    deploy: *default-deploy
    logging: *default-logging

  kong-config:
    deploy:
      restart_policy:
        condition: none
    logging: *default-logging

#  konga:
#    deploy: *default-deploy
#    logging: *default-logging

  personal-data-gateway:
    deploy: *default-deploy
    logging: *default-logging
    
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging: *default-logging

  kibana:
    deploy: *default-deploy
    logging: *default-logging

  logstash-checked-application-logs:
    deploy: *default-deploy
    logging: *default-logging

  logstash-policies-audit:
    deploy: *default-deploy
    logging: *default-logging
