version: '3.4'

x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 1m
    max-file: 1
  # TODO: Add gliderlabs/logspout as a global service in a separate stack so we can pipe logs to an external service (eg: papertrail)

services:
  mobile-frontend:
    logging: *default-logging
  transparency-frontend:
    logging: *default-logging
  transparency-backend:
    logging: *default-logging
  dispatcher:
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: $DOMAIN
      EMAIL: $RECOVERY_EMAIL
    logging: *default-logging
  consent-management-backend:
    environment:
      AUTH_CLIENT_SECRET: special-platform-secret
      AUTH_LOGIN_ENDPOINT: https://$DOMAIN/auth/realms/master/protocol/openid-connect/auth
      AUTH_USERINFO_ENDPOINT: https://$DOMAIN/auth/realms/master/protocol/openid-connect/userinfo
      AUTH_TOKEN_ENDPOINT: https://$DOMAIN/auth/realms/master/protocol/openid-connect/token
    logging: *default-logging
  data-controller-policy-management-frontend:
    logging: *default-logging
  compliance-checker:
    logging: *default-logging
  rethinkdb:
    deploy:
      placement:
        constraints:
          - node.labels.type == rethinkdb
    logging: *default-logging
  demonstrator-log-generator:
    environment:
      KEYCLOAK_ENDPOINT: https://$DOMAIN/auth
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
    logging: *default-logging
  zookeeper:
    logging: *default-logging
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
  kafka:
    environment:
      KAFKA_BROKER_ID: 0
    logging: *default-logging
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
  keycloak:
    logging: *default-logging
    environment:
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      DB_PASSWORD: $KEYCLOAK_PASSWORD
  postgres:
    logging: *default-logging
    environment:
      POSTGRES_PASSWORD: $KEYCLOAK_PASSWORD
    deploy:
      placement:
        constraints:
          - node.labels.type == database
  keycloak-init:
    logging: *default-logging
    environment:
      CLIENT_REDIRECT_URI: https://$DOMAIN/callback/*
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
