version: '2.1'
services:
  consent-ui:
    build: ./consent-management-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

  overview-ui:
    build: ./policy-checking-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"

  virtuoso:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://special.org/application"
    volumes:
      - ./database:/var/lib/virtuoso/db
      - ./config/database/data_to_load:/var/lib/virtuoso/db/toLoad
    ports:
      - "8890:8890"

    consent-backend:
      image: ubuntu

    overview-backend:
      image: ubuntu

    compliance-checker:
      image: ubuntu

    kafka:
      image: ubuntu

    zookeeper:
      image: ubuntu
