version: '3.4'

x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 1m
    max-file: 1
  # TODO: Add gliderlabs/logspout as a global service here so we can pipe logs to an external service (eg: papertrail)

services:
  mobile-frontend:
    logging: *default-logging
  transparency-frontend:
    logging: *default-logging
  transparency-backend:
    logging: *default-logging
  dispatcher:
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: demonstrator-special.tenforce.com
      EMAIL: joeri.moreno@gmail.com
    logging: *default-logging
  consent-management-frontend:
    logging: *default-logging
  consent-management-backend:
    environment:
      AUTH_CLIENT_SECRET: a0a8587f-4e33-466b-bf98-1c489b413b97
      AUTH_USERINFO_ENDPOINT: https://demonstator-special.tenforce.com/auth/realms/master/protocol/openid-connect/userinfo
      AUTH_TOKEN_ENDPOINT: https://demonstator-special.tenforce.com/auth/realms/master/protocol/openid-connect/token
    logging: *default-logging
  data-controller-policy-management-frontend:
    logging: *default-logging
  compliance-checker:
    logging: *default-logging
  rethinkdb:
    deploy:
      placement:
        constraints:
          - node.labels.type == rethinkdb
    logging: *default-logging
  demo-log-generator:
    logging: *default-logging
  zookeeper:
    logging: *default-logging
  kafka:
    environment:
      KAFKA_BROKER_ID: 0
    logging: *default-logging
    deploy:
      placement:
        constraints:
          - node.labels.type == kafka
  keycloak:
    logging: *default-logging
  postgres:
    logging: *default-logging
    deploy:
      placement:
        constraints:
          - node.labels.type == database
