{
  "certificates": null,
  "consumers": null,
  "plugins": [
    {
      "name": "oidc",
      "config": {
        "bearer_only": "no",
        "client_id": "special-platform",
        "client_secret": "84be2f39-35dd-4976-89db-57285eadf30e",
        "discovery": "https://demonstrator-special.tenforce.com/auth/realms/special/.well-known/openid-configuration",
        "filters": null,
        "introspection_endpoint": "null",
        "introspection_endpoint_auth_method": null,
        "logout_path": "/logout",
        "realm": "special",
        "recovery_page_path": null,
        "redirect_after_logout_uri": "/",
        "redirect_uri_path": "/",
        "response_type": "code",
        "scope": "all openid",
        "session_secret": null,
        "ssl_verify": "no",
        "token_endpoint_auth_method": "client_secret_post"
      },
      "enabled": true
    }
  ],
  "services": [
    {
      "name": "Keycloak",
      "host": "keycloak",
      "port": 8080,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": [
            "/auth"
          ],
          "strip_path": false,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http",
            "https"
          ],
          "methods": [
            "DELETE",
            "GET",
            "POST",
            "PUT"
          ]
        }
      ]
    },
    {
      "name": "ConsentManagementBackend",
      "host": "consent-management-backend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": null,
          "strip_path": false,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http",
            "https"
          ],
          "methods": [
            "DELETE",
            "GET",
            "POST",
            "PUT"
          ]
        }
      ]
    },
    {
      "name": "ConsentManagementFrontend",
      "host": "consent-management-frontend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": [
            "/consent"
          ],
          "strip_path": true,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http",
            "https"
          ],
          "methods": null
        }
      ]
    },
    {
      "name": "MobileFrontend",
      "host": "mobile-frontend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": [
            "/mobile"
          ],
          "strip_path": true,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http"
          ],
          "methods": [
            "GET"
          ]
        }
      ]
    },
    {
      "name": "PolicyAdminFrontend",
      "host": "policy-admin-frontend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": [
            "/policy-crud"
          ],
          "strip_path": true,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http",
            "https"
          ],
          "methods": null
        }
      ]
    },
    {
      "name": "TransparencyBackend",
      "host": "transparency-backend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000
    },
    {
      "name": "TransparencyFrontend",
      "host": "transparency-frontend",
      "port": 80,
      "protocol": "http",
      "connect_timeout": 60000,
      "read_timeout": 60000,
      "write_timeout": 60000,
      "routes": [
        {
          "paths": [
            "/transparency"
          ],
          "strip_path": true,
          "preserve_host": false,
          "regex_priority": 0,
          "hosts": null,
          "protocols": [
            "http",
            "https"
          ],
          "methods": null
        }
      ]
    }
  ],
  "upstreams": null
}
